export const handleError = e => {
    console.error(e.message)
    process.exit(1)
}